"""
C Code Exporter
===============

Generates portable C code from chip specifications.

Output files:
  - {name}.h  - Header with API declarations
  - {name}.c  - Implementation with polynomial evaluation
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple
from .trixc import ChipSpec, ChipType


@dataclass
class ExportConfig:
    """Configuration for C export."""
    prefix: str = "trix"
    include_runtime: bool = True
    target: str = "generic"  # generic, esp32, pi, x86


class CExporter:
    """
    Generates C code from chip specifications.

    The generated code is portable C99 with no external dependencies.
    """

    # Known polynomials for atoms (frozen, deterministic)
    ATOM_POLYNOMIALS = {
        'xor': ('a + b - 2*a*b', ['a', 'b']),
        'and': ('a * b', ['a', 'b']),
        'or': ('a + b - a*b', ['a', 'b']),
        'not': ('1 - a', ['a']),
        'nand': ('1 - a*b', ['a', 'b']),
        'nor': ('1 - a - b + a*b', ['a', 'b']),
        'xnor': ('1 - a - b + 2*a*b', ['a', 'b']),
        'add': ('a + b', ['a', 'b']),
        'sub': ('a - b', ['a', 'b']),
    }

    # Type mappings by bit width
    TYPE_MAP = {
        1: 'uint8_t',
        8: 'uint8_t',
        16: 'uint16_t',
        32: 'uint32_t',
    }

    @classmethod
    def generate(cls, spec: ChipSpec, config: Optional[ExportConfig] = None) -> Tuple[str, str]:
        """
        Generate C header and source for a chip.

        Returns (header_content, source_content).
        """
        config = config or ExportConfig()

        # Determine function name and type
        func_name = f"{config.prefix}_{spec.name.lower().replace(' ', '_').replace('-', '_')}"
        c_type = cls.TYPE_MAP.get(spec.bits, 'uint8_t')

        # Get polynomial and inputs
        poly, inputs = cls._get_polynomial(spec)

        # Build parameter list
        params = ', '.join(f"{c_type} {inp}" for inp in inputs)

        # Generate header
        header = cls._generate_header(spec, func_name, c_type, params, config)

        # Generate source
        source = cls._generate_source(spec, func_name, c_type, params, poly, inputs, config)

        return header, source

    @classmethod
    def _get_polynomial(cls, spec: ChipSpec) -> Tuple[str, list]:
        """Get the polynomial expression and input names for a chip."""
        name_lower = spec.name.lower()

        # Check known atoms first
        if name_lower in cls.ATOM_POLYNOMIALS:
            return cls.ATOM_POLYNOMIALS[name_lower]

        # For specified polynomial
        if spec.polynomial:
            return spec.polynomial, spec.inputs or ['a', 'b']

        # Fallback: use coefficients to reconstruct
        # For now, just return placeholder
        return f"/* coefficients: {spec.coefficients[:8]}... */", spec.inputs or ['a', 'b']

    @classmethod
    def _generate_header(cls, spec: ChipSpec, func_name: str, c_type: str,
                         params: str, config: ExportConfig) -> str:
        """Generate the .h header file."""

        guard = f"{func_name.upper()}_H"
        struct_name = f"{func_name}_t"

        return f'''/*
 * {spec.name} - Generated by The Foundry
 *
 * {spec.description or "Frozen geometric computation."}
 *
 * Size: {spec.size} bytes
 * Type: {spec.chip_type.name}
 * Bits: {spec.bits}
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Chip state (for stateful chips like processors) */
typedef struct {{
    uint8_t coefficients[{max(spec.size, 1)}];
    uint8_t state[16];  /* Internal state */
}} {struct_name};

/* Initialize chip (loads frozen coefficients) */
void {func_name}_init({struct_name} *chip);

/* Compute function */
{c_type} {func_name}({params});

/* For stateful chips: execute one step */
void {func_name}_step({struct_name} *chip);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
'''

    @classmethod
    def _generate_source(cls, spec: ChipSpec, func_name: str, c_type: str,
                         params: str, poly: str, inputs: list, config: ExportConfig) -> str:
        """Generate the .c source file."""

        struct_name = f"{func_name}_t"

        # Format coefficients as C array
        coef_lines = []
        for i in range(0, len(spec.coefficients), 16):
            chunk = spec.coefficients[i:i+16]
            coef_lines.append('    ' + ', '.join(f'{c:4d}' for c in chunk) + ',')
        coef_str = '\n'.join(coef_lines) if coef_lines else '    0'

        return f'''/*
 * {spec.name} - Generated by The Foundry
 *
 * Polynomial: {poly}
 */

#include "{func_name}.h"

/* Frozen coefficients */
static const int8_t COEFFICIENTS[{max(spec.size, 1)}] = {{
{coef_str}
}};

void {func_name}_init({struct_name} *chip) {{
    for (int i = 0; i < {spec.size}; i++) {{
        chip->coefficients[i] = (uint8_t)COEFFICIENTS[i];
    }}
    for (int i = 0; i < 16; i++) {{
        chip->state[i] = 0;
    }}
}}

{c_type} {func_name}({params}) {{
    /* Polynomial evaluation */
    return ({c_type})({poly});
}}

void {func_name}_step({struct_name} *chip) {{
    /* For stateful chips - not applicable to atoms */
    (void)chip;
}}
'''

    @classmethod
    def export(cls, spec: ChipSpec, output_dir: Path,
               config: Optional[ExportConfig] = None) -> Tuple[Path, Path]:
        """
        Export chip to C files in the specified directory.

        Returns (header_path, source_path).
        """
        config = config or ExportConfig()
        output_dir.mkdir(parents=True, exist_ok=True)

        func_name = f"{config.prefix}_{spec.name.lower().replace(' ', '_').replace('-', '_')}"

        header_content, source_content = cls.generate(spec, config)

        header_path = output_dir / f"{func_name}.h"
        source_path = output_dir / f"{func_name}.c"

        header_path.write_text(header_content)
        source_path.write_text(source_content)

        return header_path, source_path
