"""
Dispatch Table Exporter
=======================

Generates standalone C code from compiled dispatch tables + frozen shapes.

This bridges the gap between:
- compile_stable() output (Python dict)
- Thor/aarch64 deployment (pure C, no dependencies)

Usage:
    from foundry.export.dispatch_export import DispatchExporter

    # After training and compile_stable()
    dispatch_table = {0: 0, 1: 0, 2: 1, 3: 2, ...}  # class → tile
    shapes = ['xor', 'and', 'or', 'add']  # tile → shape name

    exporter = DispatchExporter(dispatch_table, shapes, name="my_alu")
    exporter.export(Path("/tmp/my_alu"))

    # Generates: my_alu.h, my_alu.c
    # Compile: gcc -O3 my_alu.c -o my_alu
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from datetime import datetime


@dataclass
class ExportConfig:
    """Configuration for dispatch export."""
    bits: int = 8
    max_classes: int = 256
    include_batch: bool = True
    inline_shapes: bool = True


# Frozen shape polynomials - the core truth
SHAPE_POLYNOMIALS = {
    'xor': ('a ^ b', 'a + b - 2*a*b'),
    'and': ('a & b', 'a * b'),
    'or': ('a | b', 'a + b - a*b'),
    'not': ('~a & 0xFF', '255 - a'),
    'nand': ('~(a & b) & 0xFF', '255 - a*b'),
    'nor': ('~(a | b) & 0xFF', '255 - a - b + a*b'),
    'xnor': ('~(a ^ b) & 0xFF', '1 - a - b + 2*a*b'),
    'add': ('(a + b) & 0xFF', 'a + b'),
    'sub': ('(a - b) & 0xFF', 'a - b'),
    'identity': ('a', 'a'),
    'zero': ('0', '0'),
    'one': ('1', '1'),
}


class DispatchExporter:
    """
    Generates C code from compiled dispatch tables.

    The output is standalone C99 with no dependencies beyond libc.
    Runs on any platform including Thor/aarch64.
    """

    def __init__(
        self,
        dispatch_table: Dict[int, int],
        shapes: List[str],
        name: str = "trix_dispatch",
        config: Optional[ExportConfig] = None
    ):
        """
        Args:
            dispatch_table: Mapping from class_id → tile_index
            shapes: List of shape names, indexed by tile
            name: Name for generated files and functions
            config: Export configuration
        """
        self.dispatch_table = dispatch_table
        self.shapes = shapes
        self.name = name
        self.config = config or ExportConfig()

        # Validate
        self._validate()

    def _validate(self):
        """Validate inputs."""
        # Check all tiles have shapes
        max_tile = max(self.dispatch_table.values()) if self.dispatch_table else 0
        if max_tile >= len(self.shapes):
            raise ValueError(
                f"Dispatch table references tile {max_tile} but only "
                f"{len(self.shapes)} shapes provided"
            )

        # Check all shapes are known
        for shape in self.shapes:
            if shape.lower() not in SHAPE_POLYNOMIALS:
                raise ValueError(f"Unknown shape: {shape}")

    def _func_name(self) -> str:
        """Generate function name from export name."""
        return self.name.lower().replace(' ', '_').replace('-', '_')

    def _c_type(self) -> str:
        """Get C type for the bit width."""
        if self.config.bits <= 8:
            return 'uint8_t'
        elif self.config.bits <= 16:
            return 'uint16_t'
        elif self.config.bits <= 32:
            return 'uint32_t'
        else:
            return 'uint64_t'

    def generate(self) -> Tuple[str, str]:
        """
        Generate C header and source.

        Returns:
            (header_content, source_content)
        """
        func = self._func_name()
        c_type = self._c_type()
        num_classes = self.config.max_classes
        num_tiles = len(self.shapes)

        header = self._generate_header(func, c_type, num_classes, num_tiles)
        source = self._generate_source(func, c_type, num_classes, num_tiles)

        return header, source

    def _generate_header(
        self, func: str, c_type: str, num_classes: int, num_tiles: int
    ) -> str:
        """Generate the .h header file."""
        guard = f"{func.upper()}_H"

        batch_decl = ""
        if self.config.include_batch:
            batch_decl = f"""
/* Batch inference */
void {func}_forward_batch(
    const int* class_ids,
    const {c_type}* a,
    const {c_type}* b,
    {c_type}* out,
    int batch_size
);
"""

        return f'''/*
 * {self.name} - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 * Classes: {num_classes}
 * Tiles: {num_tiles}
 * Shapes: {', '.join(self.shapes)}
 *
 * This is standalone C99. No dependencies beyond libc.
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Configuration */
#define {func.upper()}_NUM_CLASSES {num_classes}
#define {func.upper()}_NUM_TILES {num_tiles}
#define {func.upper()}_BITS {self.config.bits}

/* Single inference: class-driven dispatch */
{c_type} {func}_forward(int class_id, {c_type} a, {c_type} b);

/* Direct tile access (bypasses dispatch table) */
{c_type} {func}_tile(int tile_id, {c_type} a, {c_type} b);
{batch_decl}
#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
'''

    def _generate_source(
        self, func: str, c_type: str, num_classes: int, num_tiles: int
    ) -> str:
        """Generate the .c source file."""

        # Generate shape functions
        shape_funcs = self._generate_shape_functions(func, c_type)

        # Generate dispatch table
        dispatch_array = self._generate_dispatch_array(func, num_classes)

        # Generate tile dispatcher
        tile_switch = self._generate_tile_switch(func, c_type)

        # Generate batch function
        batch_func = ""
        if self.config.include_batch:
            batch_func = f"""
void {func}_forward_batch(
    const int* class_ids,
    const {c_type}* a,
    const {c_type}* b,
    {c_type}* out,
    int batch_size
) {{
    for (int i = 0; i < batch_size; i++) {{
        out[i] = {func}_forward(class_ids[i], a[i], b[i]);
    }}
}}
"""

        return f'''/*
 * {self.name} - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Routing is frozen. Shapes are polynomials. This is just math.
 */

#include "{func}.h"

/* ========== FROZEN SHAPES ========== */
{shape_funcs}

/* ========== DISPATCH TABLE ========== */
{dispatch_array}

/* ========== TILE DISPATCHER ========== */
{tile_switch}

/* ========== PUBLIC API ========== */

{c_type} {func}_forward(int class_id, {c_type} a, {c_type} b) {{
    int tile = DISPATCH_TABLE[class_id % {func.upper()}_NUM_CLASSES];
    return {func}_tile(tile, a, b);
}}
{batch_func}'''

    def _generate_shape_functions(self, func: str, c_type: str) -> str:
        """Generate inline shape functions."""
        lines = []
        seen = set()

        for shape_name in self.shapes:
            name_lower = shape_name.lower()
            if name_lower in seen:
                continue
            seen.add(name_lower)

            bitwise, poly = SHAPE_POLYNOMIALS[name_lower]

            # Use bitwise for common ops, polynomial for others
            if name_lower in ('xor', 'and', 'or', 'not', 'add', 'sub'):
                expr = bitwise
            else:
                expr = poly

            # Handle unary vs binary
            if name_lower in ('not', 'identity', 'zero', 'one'):
                lines.append(f'''static inline {c_type} shape_{name_lower}({c_type} a, {c_type} b) {{
    (void)b;  /* unused for unary op */
    return ({c_type})({expr});
}}
''')
            else:
                lines.append(f'''static inline {c_type} shape_{name_lower}({c_type} a, {c_type} b) {{
    return ({c_type})({expr});
}}
''')

        return '\n'.join(lines)

    def _generate_dispatch_array(self, func: str, num_classes: int) -> str:
        """Generate the dispatch lookup table."""
        # Build full table with default tile 0
        table = [0] * num_classes
        for class_id, tile_id in self.dispatch_table.items():
            if 0 <= class_id < num_classes:
                table[class_id] = tile_id

        # Format as C array
        lines = [f"static const int8_t DISPATCH_TABLE[{func.upper()}_NUM_CLASSES] = {{"]

        # 16 entries per line
        for i in range(0, num_classes, 16):
            chunk = table[i:i+16]
            line = "    " + ", ".join(f"{v:3d}" for v in chunk) + ","
            lines.append(line)

        lines.append("};")
        return '\n'.join(lines)

    def _generate_tile_switch(self, func: str, c_type: str) -> str:
        """Generate the tile dispatch switch."""
        cases = []
        for i, shape_name in enumerate(self.shapes):
            cases.append(f"        case {i}: return shape_{shape_name.lower()}(a, b);")

        cases_str = '\n'.join(cases)

        return f'''{c_type} {func}_tile(int tile_id, {c_type} a, {c_type} b) {{
    switch (tile_id) {{
{cases_str}
        default: return 0;
    }}
}}
'''

    def export(self, output_dir: Path) -> Tuple[Path, Path]:
        """
        Export to C files.

        Args:
            output_dir: Directory to write files

        Returns:
            (header_path, source_path)
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        func = self._func_name()
        header_content, source_content = self.generate()

        header_path = output_dir / f"{func}.h"
        source_path = output_dir / f"{func}.c"

        header_path.write_text(header_content)
        source_path.write_text(source_content)

        return header_path, source_path


def export_from_compiled_dispatch(
    compiled_dispatch,  # CompiledDispatch instance
    shapes: List[str],
    name: str,
    output_dir: Path,
    config: Optional[ExportConfig] = None
) -> Tuple[Path, Path]:
    """
    Convenience function to export directly from CompiledDispatch.

    Args:
        compiled_dispatch: A CompiledDispatch instance with compiled entries
        shapes: List of shape names per tile
        name: Export name
        output_dir: Output directory
        config: Export configuration

    Returns:
        (header_path, source_path)
    """
    # Extract dispatch table from compiled entries
    table_dict = compiled_dispatch.export_dispatch_table()

    dispatch = {}
    for class_id_str, entry in table_dict.get('entries', {}).items():
        class_id = int(class_id_str)
        tile_idx = entry.get('tile_idx', 0)
        dispatch[class_id] = tile_idx

    exporter = DispatchExporter(dispatch, shapes, name, config)
    return exporter.export(output_dir)
