"""
MDS Lattice Exporter
====================

Exports MDS lattices to C and Verilog.
The lattice IS the computation. Navigation IS the result.

Usage:
    from foundry.mds import build_adder_lattice
    from foundry.export.mds_export import MDSExporter

    lattice = build_adder_lattice(4)
    exporter = MDSExporter(lattice, name="adder_4bit")
    exporter.export_verilog(Path("./out"))  # -> adder_4bit.v
    exporter.export_c(Path("./out"))        # -> adder_4bit.h, adder_4bit.c
"""

from pathlib import Path
from typing import Tuple
from datetime import datetime

# Import MDS classes
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from mds.lattice import MDS_Lattice, Node


class MDSExporter:
    """Export MDS lattices to multiple formats."""

    # Map MDS ops to C bitwise operators
    OP_TO_C = {
        'XOR': '^',
        'AND': '&',
        'OR': '|',
        'NOT': '~',
    }

    # Map MDS ops to Verilog operators
    OP_TO_VERILOG = {
        'XOR': '^',
        'AND': '&',
        'OR': '|',
        'NOT': '~',
    }

    def __init__(self, lattice: MDS_Lattice, name: str = "mds_lattice"):
        """
        Args:
            lattice: The MDS lattice to export
            name: Name for generated files and module
        """
        self.lattice = lattice
        self.name = name

    def export_verilog(self, output_dir: Path) -> Path:
        """Export lattice to Verilog.

        Args:
            output_dir: Directory for output files

        Returns:
            Path to generated .v file
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        verilog_path = output_dir / f"{self.name}.v"
        verilog_path.write_text(self._generate_verilog())
        return verilog_path

    def export_c(self, output_dir: Path) -> Tuple[Path, Path]:
        """Export lattice to C header and source.

        Args:
            output_dir: Directory for output files

        Returns:
            Tuple of (header_path, source_path)
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        header_path = output_dir / f"{self.name}.h"
        source_path = output_dir / f"{self.name}.c"

        header_path.write_text(self._generate_header())
        source_path.write_text(self._generate_source())

        return header_path, source_path

    def _generate_verilog(self) -> str:
        """Generate Verilog module."""
        lines = []
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines.append(f"// MDS Lattice: {self.name}")
        lines.append(f"// Generated by MDSExporter")
        lines.append(f"// Date: {timestamp}")
        lines.append(f"// Nodes: {self.lattice.node_count()}")
        lines.append(f"// Levels: {len(self.lattice.levels)}")
        lines.append("")

        # Module declaration
        inputs = self.lattice.input_names
        outputs = [self.lattice.nodes[o].output_name or o for o in self.lattice.outputs]

        lines.append(f"module {self.name}(")
        for inp in inputs:
            lines.append(f"    input {inp},")
        for i, out in enumerate(outputs):
            comma = "," if i < len(outputs) - 1 else ""
            lines.append(f"    output {out}{comma}")
        lines.append(");")
        lines.append("")

        # Wire declarations for intermediate nodes
        wire_count = 0
        for level_idx, level in enumerate(self.lattice.levels):
            if level_idx == 0:
                continue  # Skip inputs
            for node_id in level:
                node = self.lattice.nodes[node_id]
                if not node.is_output:
                    lines.append(f"    wire {node_id};")
                    wire_count += 1

        if wire_count > 0:
            lines.append("")

        # Node assignments
        for level_idx, level in enumerate(self.lattice.levels):
            if level_idx == 0:
                continue
            lines.append(f"    // Level {level_idx}")
            for node_id in level:
                node = self.lattice.nodes[node_id]
                op = self.OP_TO_VERILOG[node.op]

                if node.op == 'NOT':
                    expr = f"{op}{node.src_a}"
                else:
                    expr = f"{node.src_a} {op} {node.src_b}"

                target = node.output_name if node.is_output else node_id
                lines.append(f"    assign {target} = {expr};")
            lines.append("")

        lines.append("endmodule")
        return "\n".join(lines)

    def _generate_header(self) -> str:
        """Generate C header."""
        lines = []
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        func = self.name

        inputs = self.lattice.input_names
        outputs = [self.lattice.nodes[o].output_name or o for o in self.lattice.outputs]

        lines.append(f"/*")
        lines.append(f" * MDS Lattice: {self.name}")
        lines.append(f" * Generated by MDSExporter")
        lines.append(f" * Date: {timestamp}")
        lines.append(f" * Nodes: {self.lattice.node_count()}")
        lines.append(f" */")
        lines.append("")
        lines.append(f"#ifndef {func.upper()}_H")
        lines.append(f"#define {func.upper()}_H")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("")
        lines.append(f"#define {func.upper()}_NUM_INPUTS {len(inputs)}")
        lines.append(f"#define {func.upper()}_NUM_OUTPUTS {len(outputs)}")
        lines.append("")

        # Function declaration
        params = ", ".join(f"uint8_t {inp}" for inp in inputs)
        lines.append(f"/* Navigate the {self.name} lattice")
        lines.append(f" * Inputs: {', '.join(inputs)}")
        lines.append(f" * Returns: packed outputs ({', '.join(outputs)})")
        lines.append(f" */")
        lines.append(f"uint32_t {func}_navigate({params});")
        lines.append("")
        lines.append(f"#endif /* {func.upper()}_H */")

        return "\n".join(lines)

    def _generate_source(self) -> str:
        """Generate C source with inline navigation."""
        lines = []
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        func = self.name

        lines.append(f"/*")
        lines.append(f" * MDS Lattice: {self.name}")
        lines.append(f" * Generated by MDSExporter")
        lines.append(f" * Date: {timestamp}")
        lines.append(f" * {self.lattice.node_count()} nodes, {len(self.lattice.levels)} levels")
        lines.append(f" */")
        lines.append("")
        lines.append(f'#include "{func}.h"')
        lines.append("")

        # Function definition
        inputs = self.lattice.input_names
        outputs = [self.lattice.nodes[o].output_name or o for o in self.lattice.outputs]

        params = ", ".join(f"uint8_t {inp}" for inp in inputs)
        lines.append(f"uint32_t {func}_navigate({params}) {{")

        # Node computations
        for level_idx, level in enumerate(self.lattice.levels):
            if level_idx == 0:
                continue
            lines.append(f"    /* Level {level_idx} */")
            for node_id in level:
                node = self.lattice.nodes[node_id]
                op = self.OP_TO_C[node.op]

                if node.op == 'NOT':
                    expr = f"({op}{node.src_a}) & 1"
                else:
                    expr = f"({node.src_a} {op} {node.src_b}) & 1"

                # Use output name if this is an output node
                var_name = node.output_name if node.is_output else node_id
                lines.append(f"    uint8_t {var_name} = {expr};")
            lines.append("")

        # Pack outputs
        lines.append("    /* Pack outputs */")
        pack_expr = " | ".join(f"((uint32_t){out} << {i})" for i, out in enumerate(outputs))
        lines.append(f"    return {pack_expr};")
        lines.append("}")

        return "\n".join(lines)


def demo():
    """Demo the MDS exporter."""
    import tempfile

    # Build a 4-bit adder lattice
    from mds.lattice import build_adder_lattice
    lattice = build_adder_lattice(4)

    print("MDS Lattice Structure:")
    print(lattice.visualize())
    print()

    with tempfile.TemporaryDirectory() as tmpdir:
        exporter = MDSExporter(lattice, name="adder_4bit")

        # Export Verilog
        v_path = exporter.export_verilog(Path(tmpdir))
        print(f"Generated: {v_path}")
        print("-" * 40)
        print(v_path.read_text()[:500] + "...")
        print()

        # Export C
        h_path, c_path = exporter.export_c(Path(tmpdir))
        print(f"Generated: {h_path}")
        print(f"Generated: {c_path}")
        print("-" * 40)
        print(c_path.read_text()[:500] + "...")


if __name__ == "__main__":
    demo()
