/*
 * alu_6502 - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Date: 2025-12-26 17:03:59
 * Classes: 256
 * Tiles: 11
 * Shapes: add, sub, and, or, xor, identity, identity, identity, identity, add, sub
 *
 * This is standalone C99. No dependencies beyond libc.
 */

#ifndef ALU_6502_H
#define ALU_6502_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Configuration */
#define ALU_6502_NUM_CLASSES 256
#define ALU_6502_NUM_TILES 11
#define ALU_6502_BITS 8

/* Single inference: class-driven dispatch */
uint8_t alu_6502_forward(int class_id, uint8_t a, uint8_t b);

/* Direct tile access (bypasses dispatch table) */
uint8_t alu_6502_tile(int tile_id, uint8_t a, uint8_t b);

/* Batch inference */
void alu_6502_forward_batch(
    const int* class_ids,
    const uint8_t* a,
    const uint8_t* b,
    uint8_t* out,
    int batch_size
);

#ifdef __cplusplus
}
#endif

#endif /* ALU_6502_H */
