/*
 * alu_6502 - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Routing is frozen. Shapes are polynomials. This is just math.
 */

#include "alu_6502.h"

/* ========== FROZEN SHAPES ========== */
static inline uint8_t shape_add(uint8_t a, uint8_t b) {
    return (uint8_t)((a + b) & 0xFF);
}

static inline uint8_t shape_sub(uint8_t a, uint8_t b) {
    return (uint8_t)((a - b) & 0xFF);
}

static inline uint8_t shape_and(uint8_t a, uint8_t b) {
    return (uint8_t)(a & b);
}

static inline uint8_t shape_or(uint8_t a, uint8_t b) {
    return (uint8_t)(a | b);
}

static inline uint8_t shape_xor(uint8_t a, uint8_t b) {
    return (uint8_t)(a ^ b);
}

static inline uint8_t shape_identity(uint8_t a, uint8_t b) {
    (void)b;  /* unused for unary op */
    return (uint8_t)(a);
}


/* ========== DISPATCH TABLE ========== */
static const int8_t DISPATCH_TABLE[ALU_6502_NUM_CLASSES] = {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
};

/* ========== TILE DISPATCHER ========== */
uint8_t alu_6502_tile(int tile_id, uint8_t a, uint8_t b) {
    switch (tile_id) {
        case 0: return shape_add(a, b);
        case 1: return shape_sub(a, b);
        case 2: return shape_and(a, b);
        case 3: return shape_or(a, b);
        case 4: return shape_xor(a, b);
        case 5: return shape_identity(a, b);
        case 6: return shape_identity(a, b);
        case 7: return shape_identity(a, b);
        case 8: return shape_identity(a, b);
        case 9: return shape_add(a, b);
        case 10: return shape_sub(a, b);
        default: return 0;
    }
}


/* ========== PUBLIC API ========== */

uint8_t alu_6502_forward(int class_id, uint8_t a, uint8_t b) {
    int tile = DISPATCH_TABLE[class_id % ALU_6502_NUM_CLASSES];
    return alu_6502_tile(tile, a, b);
}

void alu_6502_forward_batch(
    const int* class_ids,
    const uint8_t* a,
    const uint8_t* b,
    uint8_t* out,
    int batch_size
) {
    for (int i = 0; i < batch_size; i++) {
        out[i] = alu_6502_forward(class_ids[i], a[i], b[i]);
    }
}
