/*
 * alu_router - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Date: 2025-12-25 01:30:04
 * Classes: 256
 * Tiles: 4
 * Shapes: add, sub, xor, and
 *
 * This is standalone C99. No dependencies beyond libc.
 */

#ifndef ALU_ROUTER_H
#define ALU_ROUTER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Configuration */
#define ALU_ROUTER_NUM_CLASSES 256
#define ALU_ROUTER_NUM_TILES 4
#define ALU_ROUTER_BITS 8

/* Single inference: class-driven dispatch */
uint8_t alu_router_forward(int class_id, uint8_t a, uint8_t b);

/* Direct tile access (bypasses dispatch table) */
uint8_t alu_router_tile(int tile_id, uint8_t a, uint8_t b);

/* Batch inference */
void alu_router_forward_batch(
    const int* class_ids,
    const uint8_t* a,
    const uint8_t* b,
    uint8_t* out,
    int batch_size
);

#ifdef __cplusplus
}
#endif

#endif /* ALU_ROUTER_H */
