/*
 * alu_router - Compiled Dispatch Export
 * Generated by The Foundry
 *
 * Routing is frozen. Shapes are polynomials. This is just math.
 */

#include "alu_router.h"

/* ========== FROZEN SHAPES ========== */
static inline uint8_t shape_add(uint8_t a, uint8_t b) {
    return (uint8_t)((a + b) & 0xFF);
}

static inline uint8_t shape_sub(uint8_t a, uint8_t b) {
    return (uint8_t)((a - b) & 0xFF);
}

static inline uint8_t shape_xor(uint8_t a, uint8_t b) {
    return (uint8_t)(a ^ b);
}

static inline uint8_t shape_and(uint8_t a, uint8_t b) {
    return (uint8_t)(a & b);
}


/* ========== DISPATCH TABLE ========== */
static const int8_t DISPATCH_TABLE[ALU_ROUTER_NUM_CLASSES] = {
      3,   2,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   2,   0,   2,   0,   2,
      3,   2,   3,   2,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   1,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0,   2,   0,   2,
      3,   2,   3,   2,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   1,   2,   1,   2,   1,   2,   2,   2,   2,   2,   0,   2,   0,   2,
      3,   1,   3,   1,   3,   2,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   2,   2,   0,   2,
      3,   1,   3,   1,   3,   1,   3,   0,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,
      1,   1,   3,   1,   3,   1,   3,   1,   3,   0,   3,   0,   3,   0,   3,   0,
      1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,
      1,   1,   1,   1,   3,   1,   3,   1,   3,   1,   3,   1,   3,   0,   3,   0,
      1,   1,   1,   1,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,   1,   2,
      1,   1,   1,   1,   1,   1,   3,   1,   3,   1,   3,   1,   3,   1,   3,   0,
      1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   1,   2,   1,   2,   1,   2,
};

/* ========== TILE DISPATCHER ========== */
uint8_t alu_router_tile(int tile_id, uint8_t a, uint8_t b) {
    switch (tile_id) {
        case 0: return shape_add(a, b);
        case 1: return shape_sub(a, b);
        case 2: return shape_xor(a, b);
        case 3: return shape_and(a, b);
        default: return 0;
    }
}


/* ========== PUBLIC API ========== */

uint8_t alu_router_forward(int class_id, uint8_t a, uint8_t b) {
    int tile = DISPATCH_TABLE[class_id % ALU_ROUTER_NUM_CLASSES];
    return alu_router_tile(tile, a, b);
}

void alu_router_forward_batch(
    const int* class_ids,
    const uint8_t* a,
    const uint8_t* b,
    uint8_t* out,
    int batch_size
) {
    for (int i = 0; i < batch_size; i++) {
        out[i] = alu_router_forward(class_ids[i], a[i], b[i]);
    }
}
