"""
Core foundry - Shape definition and management.
"""
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Tuple
import time


@dataclass
class Term:
    """A single polynomial term: coefficient * product(variables)."""
    coefficient: int
    variables: Tuple[str, ...]

    def evaluate(self, bindings: Dict[str, int]) -> int:
        """Evaluate this term with given variable bindings."""
        result = self.coefficient
        for var in self.variables:
            result *= bindings[var]
        return result

    def __str__(self) -> str:
        if not self.variables:
            return str(self.coefficient)
        var_str = "*".join(self.variables)
        if self.coefficient == 1:
            return var_str
        elif self.coefficient == -1:
            return f"-{var_str}"
        else:
            return f"{self.coefficient}*{var_str}"


@dataclass
class Shape:
    """A frozen computational shape."""
    name: str
    func: Callable
    bits: int = 8
    arity: int = 2  # 1=unary, 2=binary
    polynomial: str = ""
    terms: List[Term] = field(default_factory=list)
    _validated: bool = False
    _validation_result: Optional[Tuple[int, int]] = None
    _source_expr: str = ""  # Original lambda expression for custom shapes

    def __call__(self, *args) -> int:
        """Execute the shape."""
        if len(args) != self.arity:
            raise ValueError(f"{self.name} expects {self.arity} arguments, got {len(args)}")
        result = self.func(*args)
        # Mask to bits
        mask = (1 << self.bits) - 1
        return result & mask

    def validate(self, callback: Optional[Callable] = None) -> Tuple[int, int]:
        """Exhaustively validate against truth table."""
        mask = (1 << self.bits) - 1
        total = 0
        passed = 0

        if self.arity == 1:
            total = 1 << self.bits
            for a in range(1 << self.bits):
                expected = self.func(a) & mask
                got = self(a)
                if expected == got:
                    passed += 1
                if callback:
                    callback(passed, total)
        else:  # binary
            total = (1 << self.bits) ** 2
            count = 0
            for a in range(1 << self.bits):
                for b in range(1 << self.bits):
                    expected = self.func(a, b) & mask
                    got = self(a, b)
                    if expected == got:
                        passed += 1
                    count += 1
                    if callback and count % 1000 == 0:
                        callback(count, total)
            if callback:
                callback(total, total)

        self._validated = True
        self._validation_result = (passed, total)
        return (passed, total)

    def export_c(self) -> str:
        """Export shape to C code."""
        type_map = {8: "uint8_t", 16: "uint16_t", 32: "uint32_t"}
        ctype = type_map.get(self.bits, "uint32_t")

        if self.arity == 1:
            params = f"{ctype} a"
            body = self._generate_c_body_unary()
        else:
            params = f"{ctype} a, {ctype} b"
            body = self._generate_c_body_binary()

        return f"""// Generated by TriX Forge
// Shape: {self.name.upper()}
// Polynomial: {self.polynomial}
// Validated: {self._validation_result[0] if self._validated else '?'}/{self._validation_result[1] if self._validated else '?'}

#include <stdint.h>

{ctype} trix_{self.name}({params}) {{
    return {body};
}}
"""

    def _generate_c_body_binary(self) -> str:
        """Generate C expression for binary operation."""
        # Use polynomial form for known shapes
        poly_map = {
            'xor': 'a + b - 2 * a * b',
            'and': 'a * b',
            'or': 'a + b - a * b',
            'nand': '1 - a * b',
            'nor': '1 - a - b + a * b',
            'xnor': '1 - a - b + 2 * a * b',
            'add': '(a + b) & 0xFF',
            'sub': '(a - b) & 0xFF',
            'mul': '(a * b) & 0xFF',
        }
        if self.name in poly_map:
            return poly_map[self.name]
        # For custom shapes, convert lambda body to C
        if self._source_expr:
            # Extract body from lambda expression
            # lambda a, b: BODY -> BODY
            if ':' in self._source_expr:
                body = self._source_expr.split(':', 1)[1].strip()
                # Convert Python operators to C
                c_body = body.replace('^', ' ^ ')  # XOR
                c_body = c_body.replace('&', ' & ')  # AND
                c_body = c_body.replace('|', ' | ')  # OR
                c_body = c_body.replace('0xFF', '0xFF')
                c_body = c_body.replace('0xff', '0xFF')
                return f"({c_body})"
        return f"/* custom shape - see polynomial */"

    def _generate_c_body_unary(self) -> str:
        """Generate C expression for unary operation."""
        poly_map = {
            'not': '~a & 0xFF',
        }
        if self.name in poly_map:
            return poly_map[self.name]
        return f"/* custom */ (~a & 0xFF)"


class Foundry:
    """The shape foundry - register, validate, export."""

    def __init__(self, bits: int = 8):
        self.bits = bits
        self.shapes: Dict[str, Shape] = {}
        self._custom_counter = 0

    def atom(self, name: str, func: Callable, arity: int = 2) -> Shape:
        """Register an atomic shape from a function."""
        shape = Shape(
            name=name,
            func=func,
            bits=self.bits,
            arity=arity,
            polynomial=self._derive_polynomial(name, func, arity),
        )
        self.shapes[name] = shape
        return shape

    def custom(self, expr: str) -> Shape:
        """Create a shape from a lambda expression string."""
        # Parse and validate the expression
        expr = expr.strip()
        if not expr.startswith("lambda"):
            raise ValueError("Expression must be a lambda, e.g., 'lambda a, b: a ^ b'")

        try:
            func = eval(expr)
        except SyntaxError as e:
            raise ValueError(f"Syntax error in expression: {e}")

        # Determine arity
        import inspect
        sig = inspect.signature(func)
        arity = len(sig.parameters)

        if arity < 1 or arity > 3:
            raise ValueError(f"Lambda must have 1-3 parameters, got {arity}")

        name = f"custom_{self._custom_counter}"
        self._custom_counter += 1

        shape = self.atom(name, func, arity)
        shape._source_expr = expr  # Store for C export
        return shape

    def _derive_polynomial(self, name: str, func: Callable, arity: int) -> str:
        """Derive polynomial representation if known."""
        known = {
            'xor': 'a + b - 2ab',
            'and': 'ab',
            'or': 'a + b - ab',
            'not': '1 - a',
            'nand': '1 - ab',
            'nor': '1 - a - b + ab',
            'xnor': '1 - a - b + 2ab',
            'add': '(a + b) mod 2^n',
            'sub': '(a - b) mod 2^n',
            'mul': '(a * b) mod 2^n',
        }
        return known.get(name, f"f({', '.join('abcdefgh'[:arity])})")

    def get(self, name: str) -> Optional[Shape]:
        """Get a shape by name."""
        return self.shapes.get(name)

    def list_shapes(self) -> List[str]:
        """List all registered shapes."""
        return list(self.shapes.keys())


# Global foundry instance
_global_foundry = Foundry(bits=8)


def get_foundry() -> Foundry:
    """Get the global foundry instance."""
    return _global_foundry


def register_builtin(name: str, func: Callable, polynomial: str, arity: int = 2) -> Shape:
    """Register a built-in shape."""
    shape = Shape(
        name=name,
        func=func,
        bits=8,
        arity=arity,
        polynomial=polynomial,
    )
    _global_foundry.shapes[name] = shape
    return shape
