"""
CUDA kernel generation for XORPU shapes.

Generates CUDA C++ kernels from ShapeTerms specifications for GPU validation.

Usage:
    from trix.forge.cuda import shape_to_cuda, export_cuda

    # Generate single shape kernel
    xor_shape = generate_xor_shape(bits=32)
    cuda_code = shape_to_cuda(xor_shape)

    # Export all shapes
    shapes = generate_all_shapes(bits=32)
    export_cuda(shapes, "cuda/")
"""

from typing import Dict, List, Optional
from pathlib import Path
from datetime import datetime

from .term import ShapeTerms, Term, BitTerms, FAST_PATH_SHAPES


# =============================================================================
# CUDA GENERATION
# =============================================================================

def _term_to_cuda(term: Term, bits: int) -> str:
    """
    Convert a term to CUDA expression.

    For a[i], b[i] indexing where:
    - indices 0 to bits-1 are a bits
    - indices bits to 2*bits-1 are b bits
    """
    if term.is_constant():
        return f"{term.coefficient & 1}"  # Only LSB matters for XOR

    var_strs = []
    for v in term.variables:
        if v < bits:
            var_strs.append(f"((a >> {v}) & 1)")
        else:
            var_strs.append(f"((b >> {v - bits}) & 1)")

    if len(var_strs) == 1:
        return var_strs[0]
    else:
        # AND of multiple variables
        return " & ".join(var_strs)


def _is_simple_shape(shape: ShapeTerms) -> Optional[str]:
    """Check if shape is a simple recognizable pattern."""
    name = shape.name.lower()
    if name in FAST_PATH_SHAPES:
        return name
    return None


def _generate_simple_kernel(shape_type: str, bits: int) -> str:
    """Generate optimized CUDA for simple shapes."""
    type_name = f"uint{bits}_t" if bits in [8, 16, 32, 64] else "uint32_t"

    if shape_type == "xor":
        return f"return a ^ b;"
    elif shape_type == "and":
        return f"return a & b;"
    elif shape_type == "or":
        return f"return a | b;"
    elif shape_type == "not":
        return f"return ~a;"
    elif shape_type == "nand":
        return f"return ~(a & b);"
    elif shape_type == "nor":
        return f"return ~(a | b);"
    elif shape_type == "xnor":
        return f"return ~(a ^ b);"
    elif shape_type == "nop":
        return f"return a;"
    else:
        return None


def shape_to_cuda(
    shape: ShapeTerms,
    optimize: bool = True,
    include_header: bool = True,
    device_only: bool = False,
) -> str:
    """
    Generate CUDA kernel for a shape.

    Args:
        shape: The shape specification
        optimize: If True, recognize simple patterns
        include_header: If True, include generation metadata
        device_only: If True, generate __device__ function only

    Returns:
        CUDA kernel as string
    """
    lines = []
    bits = shape.output_bits
    type_name = f"uint{bits}_t" if bits in [8, 16, 32, 64] else "uint32_t"

    # Header
    if include_header:
        lines.append(f"// Auto-generated by trix.forge")
        lines.append(f"// Generated: {datetime.now().isoformat()}")
        lines.append(f"// Shape: {shape.name} ({bits}-bit)")
        lines.append(f"// Total terms: {shape.total_terms()}")
        lines.append("")

    # Check for simple patterns
    simple_type = _is_simple_shape(shape) if optimize else None

    func_prefix = "__device__ __forceinline__" if device_only else "__global__"

    if simple_type:
        # Optimized simple kernel
        if device_only:
            lines.append(f"__device__ __forceinline__ {type_name} xorpu_{shape.name}({type_name} a, {type_name} b) {{")
        else:
            lines.append(f"__global__ void xorpu_{shape.name}({type_name}* a, {type_name}* b, {type_name}* result, int n) {{")
            lines.append(f"    int idx = blockIdx.x * blockDim.x + threadIdx.x;")
            lines.append(f"    if (idx >= n) return;")
            lines.append(f"    {type_name} av = a[idx];")
            lines.append(f"    {type_name} bv = b[idx];")

        body = _generate_simple_kernel(simple_type, bits)
        if device_only:
            lines.append(f"    {body}")
        else:
            lines.append(f"    result[idx] = av ^ bv;" if simple_type == "xor" else f"    result[idx] = {body.replace('return ', '').replace(';', '').replace('a', 'av').replace('b', 'bv')};")
        lines.append("}")
    else:
        # Full polynomial kernel
        if device_only:
            lines.append(f"__device__ __forceinline__ {type_name} xorpu_{shape.name}({type_name} a, {type_name} b) {{")
            lines.append(f"    {type_name} result = 0;")
        else:
            lines.append(f"__global__ void xorpu_{shape.name}({type_name}* a_arr, {type_name}* b_arr, {type_name}* result_arr, int n) {{")
            lines.append(f"    int idx = blockIdx.x * blockDim.x + threadIdx.x;")
            lines.append(f"    if (idx >= n) return;")
            lines.append(f"    {type_name} a = a_arr[idx];")
            lines.append(f"    {type_name} b = b_arr[idx];")
            lines.append(f"    {type_name} result = 0;")

        lines.append("")

        # Generate each output bit
        for bit_terms in shape.bit_terms:
            bit_idx = bit_terms.bit_index
            terms_exprs = []

            for term in bit_terms.terms:
                if term.coefficient in [1, -1]:
                    terms_exprs.append(_term_to_cuda(term, bits))
                elif term.coefficient in [2, -2]:
                    # Coefficient 2 vanishes in GF(2)
                    continue

            if terms_exprs:
                xor_expr = " ^ ".join(terms_exprs)
                lines.append(f"    result |= (({xor_expr}) << {bit_idx});")

        lines.append("")
        if device_only:
            lines.append(f"    return result;")
        else:
            lines.append(f"    result_arr[idx] = result;")
        lines.append("}")

    return "\n".join(lines)


def generate_cuda_header(bits: int = 32) -> str:
    """Generate CUDA header with includes and type definitions."""
    return f"""// XORPU CUDA Kernels
// Auto-generated by trix.forge
// Generated: {datetime.now().isoformat()}

#include <cuda_runtime.h>
#include <stdint.h>
#include <stdio.h>

#define BLOCK_SIZE 256

// Error checking macro
#define CUDA_CHECK(call) do {{ \\
    cudaError_t err = call; \\
    if (err != cudaSuccess) {{ \\
        fprintf(stderr, "CUDA error at %s:%d: %s\\n", __FILE__, __LINE__, cudaGetErrorString(err)); \\
        exit(1); \\
    }} \\
}} while(0)

"""


def generate_cuda_test_harness(shapes: Dict[str, ShapeTerms], bits: int = 32) -> str:
    """Generate test harness for CUDA kernels."""
    type_name = f"uint{bits}_t" if bits in [8, 16, 32, 64] else "uint32_t"

    lines = []
    lines.append(f"""
// =============================================================================
// TEST HARNESS
// =============================================================================

void test_shape(const char* name, void (*kernel)({type_name}*, {type_name}*, {type_name}*, int),
                {type_name} a, {type_name} b, {type_name} expected) {{
    {type_name} *d_a, *d_b, *d_result;
    {type_name} h_result;

    CUDA_CHECK(cudaMalloc(&d_a, sizeof({type_name})));
    CUDA_CHECK(cudaMalloc(&d_b, sizeof({type_name})));
    CUDA_CHECK(cudaMalloc(&d_result, sizeof({type_name})));

    CUDA_CHECK(cudaMemcpy(d_a, &a, sizeof({type_name}), cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_b, &b, sizeof({type_name}), cudaMemcpyHostToDevice));

    kernel<<<1, 1>>>(d_a, d_b, d_result, 1);
    CUDA_CHECK(cudaDeviceSynchronize());

    CUDA_CHECK(cudaMemcpy(&h_result, d_result, sizeof({type_name}), cudaMemcpyDeviceToHost));

    const char* status = (h_result == expected) ? "PASS" : "FAIL";
    printf("  %s: %s(0x%X, 0x%X) = 0x%X (expected 0x%X) [%s]\\n",
           status, name, a, b, h_result, expected, status);

    cudaFree(d_a);
    cudaFree(d_b);
    cudaFree(d_result);
}}

int main() {{
    printf("XORPU CUDA Validation\\n");
    printf("=====================\\n\\n");

    // Test XOR
    printf("Testing XOR:\\n");
    test_shape("xor", xorpu_xor, 0xAAAAAAAA, 0x55555555, 0xFFFFFFFF);
    test_shape("xor", xorpu_xor, 0xFFFFFFFF, 0xFFFFFFFF, 0x00000000);
    test_shape("xor", xorpu_xor, 0x12345678, 0x00000000, 0x12345678);

    // Test AND
    printf("\\nTesting AND:\\n");
    test_shape("and", xorpu_and, 0xAAAAAAAA, 0x55555555, 0x00000000);
    test_shape("and", xorpu_and, 0xFFFFFFFF, 0x0F0F0F0F, 0x0F0F0F0F);

    // Test OR
    printf("\\nTesting OR:\\n");
    test_shape("or", xorpu_or, 0xAAAAAAAA, 0x55555555, 0xFFFFFFFF);
    test_shape("or", xorpu_or, 0x00000000, 0x12345678, 0x12345678);

    printf("\\nValidation complete.\\n");
    return 0;
}}
""")
    return "\n".join(lines)


def export_cuda(
    shapes: Dict[str, ShapeTerms],
    output_dir: str,
    optimize: bool = True,
) -> List[str]:
    """
    Export multiple shapes to CUDA files.

    Args:
        shapes: Dictionary of shape name -> ShapeTerms
        output_dir: Directory to write files
        optimize: If True, recognize simple patterns

    Returns:
        List of generated file paths
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    bits = next(iter(shapes.values())).output_bits if shapes else 32
    generated_files = []

    # Generate unified kernel file
    cuda_content = generate_cuda_header(bits)

    for name in sorted(shapes.keys()):
        shape = shapes[name]
        cuda_content += shape_to_cuda(shape, optimize=optimize, include_header=False)
        cuda_content += "\n\n"

    cuda_content += generate_cuda_test_harness(shapes, bits)

    kernel_path = output_path / "xorpu_kernels.cu"
    with open(kernel_path, 'w') as f:
        f.write(cuda_content)
    generated_files.append(str(kernel_path))

    # Generate Makefile
    makefile = f"""# XORPU CUDA Makefile
# Auto-generated by trix.forge

NVCC = nvcc
NVCC_FLAGS = -O3 -arch=native

all: xorpu_test

xorpu_test: xorpu_kernels.cu
\t$(NVCC) $(NVCC_FLAGS) -o $@ $<

clean:
\trm -f xorpu_test

run: xorpu_test
\t./xorpu_test

.PHONY: all clean run
"""
    makefile_path = output_path / "Makefile"
    with open(makefile_path, 'w') as f:
        f.write(makefile)
    generated_files.append(str(makefile_path))

    return generated_files


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "shape_to_cuda",
    "export_cuda",
    "generate_cuda_header",
    "generate_cuda_test_harness",
]
