"""
C code generation for frozen polynomials.

Supports three modes:
- Standard: BitExpr list (expanded polynomials)
- Factored: FactoredResult with intermediate variables (linear size)
- Compact: Loop-based O(1) code size (same math, sequential execution)
"""

from typing import Dict, List, Tuple
from .parser import Module, Port, OpType
from .composer import BitExpr, FactoredResult


def emit_c(module: Module, bit_exprs: List[BitExpr]) -> Tuple[str, str]:
    """
    Generate C header and source for frozen module.

    Args:
        module: Parsed Verilog module
        bit_exprs: Composed bit expressions

    Returns:
        (header_content, source_content)
    """
    name = module.name

    # Collect inputs and outputs with widths
    inputs = []
    outputs = []
    for port in module.ports.values():
        if port.direction == "input":
            inputs.append((port.name, port.width))
        else:
            outputs.append((port.name, port.width))

    header = _generate_header(name, inputs, outputs)
    source = _generate_source(name, inputs, outputs, bit_exprs)

    return header, source


def _c_type(bits: int) -> str:
    """Get C type for bit width."""
    if bits <= 8:
        return "uint8_t"
    if bits <= 16:
        return "uint16_t"
    if bits <= 32:
        return "uint32_t"
    if bits <= 64:
        return "uint64_t"
    # For 65+ bits, use 128-bit type (GCC extension)
    return "__uint128_t"


def _generate_header(name: str, inputs: List[Tuple[str, int]],
                     outputs: List[Tuple[str, int]]) -> str:
    """Generate C header file."""
    guard = f"FROZEN_{name.upper()}_H"

    # Build parameter list
    params = []
    for n, bits in inputs:
        params.append(f"{_c_type(bits)} {n}")
    for n, bits in outputs:
        params.append(f"{_c_type(bits)} *{n}")

    param_str = ", ".join(params) if params else "void"

    return f'''/*
 * Frozen {name} - Generated by TriX Forge
 *
 * Pure polynomial computation. No inference.
 * This is 100% deterministic frozen geometry.
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>

/*
 * Evaluate frozen {name}.
 *
 * Inputs are passed by value.
 * Outputs are written through pointers.
 */
void frozen_{name}({param_str});

#endif /* {guard} */
'''


def _generate_source(name: str, inputs: List[Tuple[str, int]],
                     outputs: List[Tuple[str, int]],
                     bit_exprs: List[BitExpr]) -> str:
    """Generate C source file."""

    # Build parameter list
    params = []
    for n, bits in inputs:
        params.append(f"{_c_type(bits)} {n}")
    for n, bits in outputs:
        params.append(f"{_c_type(bits)} *{n}")

    param_str = ", ".join(params) if params else "void"

    # Generate bit extraction for inputs
    bit_extracts = []
    for in_name, bits in inputs:
        if bits > 1:
            for i in range(bits):
                bit_extracts.append(
                    f"    int {in_name}_{i} = ({in_name} >> {i}) & 1;"
                )
        else:
            bit_extracts.append(f"    int {in_name}_0 = {in_name} & 1;")

    # Generate polynomial evaluations
    poly_evals = []
    for expr in bit_exprs:
        # Clean up the polynomial for C
        poly = expr.polynomial
        # Use _bit suffix to avoid conflict with output pointer parameter
        poly_evals.append(f"    int {expr.name}_bit = {poly};")

    # Generate output packing
    output_packs = []
    for out_name, bits in outputs:
        if bits > 1:
            terms = []
            for i in range(bits):
                bit_name = f"{out_name}_{i}"
                # Check if this bit was computed
                if any(e.name == bit_name for e in bit_exprs):
                    terms.append(f"(({_c_type(bits)}){bit_name}_bit << {i})")
            if terms:
                output_packs.append(f"    *{out_name} = {' | '.join(terms)};")
            else:
                output_packs.append(f"    *{out_name} = 0;")
        else:
            # Single-bit output - always use _0 suffix
            bit_name = f"{out_name}_0"
            if any(e.name == bit_name for e in bit_exprs):
                output_packs.append(f"    *{out_name} = {bit_name}_bit;")
            else:
                output_packs.append(f"    *{out_name} = 0;")

    extract_section = "\n".join(bit_extracts) if bit_extracts else "    /* No inputs */"
    poly_section = "\n".join(poly_evals) if poly_evals else "    /* No computation */"
    pack_section = "\n".join(output_packs) if output_packs else "    /* No outputs */"

    return f'''/*
 * Frozen {name} - Generated by TriX Forge
 *
 * This is pure polynomial computation.
 * No neural network. No inference. Just math.
 *
 * The polynomials encode the exact behavior of the original Verilog.
 */

#include "frozen_{name}.h"

void frozen_{name}({param_str}) {{
    /* Extract individual bits from inputs */
{extract_section}

    /* Evaluate polynomials for each output bit */
{poly_section}

    /* Pack output bits */
{pack_section}
}}
'''


def emit_c_factored(module: Module, factored: FactoredResult) -> Tuple[str, str]:
    """
    Generate C code from factored composition result.

    Uses intermediate variables for carries, resulting in O(n) code size
    instead of O(2^n) for expanded polynomials.
    """
    name = module.name

    # Collect inputs and outputs with widths
    inputs = []
    outputs = []
    for port in module.ports.values():
        if port.direction == "input":
            inputs.append((port.name, port.width))
        else:
            outputs.append((port.name, port.width))

    header = _generate_header(name, inputs, outputs)
    source = _generate_source_factored(name, inputs, outputs, factored)

    return header, source


def _generate_source_factored(name: str, inputs: List[Tuple[str, int]],
                               outputs: List[Tuple[str, int]],
                               factored: FactoredResult) -> str:
    """Generate C source with factored intermediate variables."""

    # Build parameter list
    params = []
    for n, bits in inputs:
        params.append(f"{_c_type(bits)} {n}")
    for n, bits in outputs:
        params.append(f"{_c_type(bits)} *{n}")

    param_str = ", ".join(params) if params else "void"

    # Generate bit extraction for inputs
    bit_extracts = []
    for in_name, bits in inputs:
        if bits > 1:
            for i in range(bits):
                bit_extracts.append(
                    f"    int {in_name}_{i} = ({in_name} >> {i}) & 1;"
                )
        else:
            bit_extracts.append(f"    int {in_name}_0 = {in_name} & 1;")

    # Generate intermediate variables (carries)
    intermediates = []
    for var_name, expr in factored.intermediates:
        intermediates.append(f"    int {var_name} = {expr};")

    # Generate output bit computations
    output_bits = []
    for bit_name, expr in factored.outputs:
        output_bits.append(f"    int {bit_name}_bit = {expr};")

    # Generate output packing
    output_packs = []
    output_bit_names = {name for name, _ in factored.outputs}

    for out_name, bits in outputs:
        if bits > 1:
            terms = []
            for i in range(bits):
                bit_name = f"{out_name}_{i}"
                if bit_name in output_bit_names:
                    terms.append(f"(({_c_type(bits)}){bit_name}_bit << {i})")
            if terms:
                output_packs.append(f"    *{out_name} = {' | '.join(terms)};")
            else:
                output_packs.append(f"    *{out_name} = 0;")
        else:
            bit_name = f"{out_name}_0"
            if bit_name in output_bit_names:
                output_packs.append(f"    *{out_name} = {bit_name}_bit;")
            else:
                output_packs.append(f"    *{out_name} = 0;")

    extract_section = "\n".join(bit_extracts) if bit_extracts else "    /* No inputs */"
    intermediate_section = "\n".join(intermediates) if intermediates else ""
    output_section = "\n".join(output_bits) if output_bits else "    /* No computation */"
    pack_section = "\n".join(output_packs) if output_packs else "    /* No outputs */"

    # Build the poly section with intermediates first, then outputs
    if intermediate_section:
        poly_section = f"{intermediate_section}\n\n    /* Output bits */\n{output_section}"
    else:
        poly_section = output_section

    return f'''/*
 * Frozen {name} - Generated by TriX Forge (Factored)
 *
 * This is pure polynomial computation with factored carries.
 * Linear code size: O(n) instead of O(2^n).
 *
 * No neural network. No inference. Just math.
 */

#include "frozen_{name}.h"

void frozen_{name}({param_str}) {{
    /* Extract individual bits from inputs */
{extract_section}

    /* Evaluate polynomials with intermediate carries */
{poly_section}

    /* Pack output bits */
{pack_section}
}}
'''


def emit_c_compact(module: Module) -> Tuple[str, str]:
    """
    Generate compact loop-based C code.

    O(1) code size regardless of bit width.
    Same polynomial math, but executed sequentially in a loop.

    Tradeoffs vs expanded:
    - Pro: Tiny code size (600 bytes vs 1GB for 2M-bit)
    - Pro: Works for any bit width without regeneration
    - Con: Sequential execution (not parallelizable)
    - Con: Variable timing (not crypto-safe)
    """
    name = module.name

    # Analyze the module to determine operation type
    inputs = [(p.name, p.width) for p in module.ports.values() if p.direction == "input"]
    outputs = [(p.name, p.width) for p in module.ports.values() if p.direction == "output"]

    if not inputs or not outputs:
        raise ValueError("Module must have inputs and outputs")

    # Detect operation type from assignments
    op_type = None
    for assign in module.assignments:
        if assign.expr.op == OpType.ADD:
            op_type = "add"
            break
        elif assign.expr.op == OpType.SUB:
            op_type = "sub"
            break
        elif assign.expr.op == OpType.XOR:
            op_type = "xor"
            break
        elif assign.expr.op == OpType.AND:
            op_type = "and"
            break
        elif assign.expr.op == OpType.OR:
            op_type = "or"
            break

    # Get bit widths
    in_bits = max(w for _, w in inputs)
    out_bits = max(w for _, w in outputs)

    header = _generate_compact_header(name, inputs, outputs)

    if op_type == "add":
        source = _generate_compact_adder(name, inputs, outputs, in_bits, out_bits)
    elif op_type == "sub":
        source = _generate_compact_subtractor(name, inputs, outputs, in_bits, out_bits)
    elif op_type in ("xor", "and", "or"):
        source = _generate_compact_bitwise(name, inputs, outputs, in_bits, op_type)
    else:
        raise ValueError(f"Compact mode not supported for operation: {op_type}")

    return header, source


def _generate_compact_header(name: str, inputs: List[Tuple[str, int]],
                              outputs: List[Tuple[str, int]]) -> str:
    """Generate header for compact module."""
    guard = f"FROZEN_{name.upper()}_H"

    # For compact mode, we use byte arrays for arbitrary width
    max_in_bits = max(w for _, w in inputs)
    max_out_bits = max(w for _, w in outputs)

    in_bytes = (max_in_bits + 7) // 8
    out_bytes = (max_out_bits + 7) // 8

    return f'''/*
 * Frozen {name} - Generated by TriX Forge (Compact)
 *
 * Loop-based polynomial computation.
 * O(1) code size for any bit width.
 *
 * Same math as expanded form, sequential execution.
 */

#ifndef {guard}
#define {guard}

#include <stdint.h>
#include <string.h>

#define {name.upper()}_IN_BITS {max_in_bits}
#define {name.upper()}_OUT_BITS {max_out_bits}
#define {name.upper()}_IN_BYTES {in_bytes}
#define {name.upper()}_OUT_BYTES {out_bytes}

/*
 * Evaluate frozen {name}.
 *
 * Inputs and outputs are byte arrays (little-endian bit ordering).
 * Bit 0 is LSB of byte 0.
 */
void frozen_{name}(const uint8_t *a, const uint8_t *b, uint8_t *result);

#endif /* {guard} */
'''


def _generate_compact_adder(name: str, inputs: List[Tuple[str, int]],
                             outputs: List[Tuple[str, int]],
                             in_bits: int, out_bits: int) -> str:
    """Generate compact loop-based adder."""
    out_bytes = (out_bits + 7) // 8

    return f'''/*
 * Frozen {name} - Generated by TriX Forge (Compact)
 *
 * Polynomial ripple-carry addition in loop form.
 * Same math as expanded, O(1) code size.
 */

#include "frozen_{name}.h"

/* Polynomial primitives */
static inline int poly_xor(int a, int b) {{ return a + b - 2*a*b; }}
static inline int poly_and(int a, int b) {{ return a * b; }}
static inline int poly_or(int a, int b) {{ return a + b - a*b; }}

void frozen_{name}(const uint8_t *a, const uint8_t *b, uint8_t *result) {{
    int carry = 0;

    /* Clear result */
    memset(result, 0, {out_bytes});

    /* Ripple-carry addition using polynomial arithmetic */
    for (int i = 0; i < {in_bits}; i++) {{
        /* Extract bits */
        int ai = (a[i >> 3] >> (i & 7)) & 1;
        int bi = (b[i >> 3] >> (i & 7)) & 1;

        /* Sum bit: (a XOR b) XOR carry */
        int ab_xor = poly_xor(ai, bi);
        int sum_bit = poly_xor(ab_xor, carry);

        /* Carry out: (a AND b) OR (carry AND (a XOR b)) */
        int ab_and = poly_and(ai, bi);
        int carry_and_xor = poly_and(carry, ab_xor);
        carry = poly_or(ab_and, carry_and_xor);

        /* Store sum bit */
        if (sum_bit)
            result[i >> 3] |= (1 << (i & 7));
    }}

    /* Store final carry as MSB */
    if (carry && {out_bits} > {in_bits})
        result[{in_bits} >> 3] |= (1 << ({in_bits} & 7));
}}
'''


def _generate_compact_subtractor(name: str, inputs: List[Tuple[str, int]],
                                  outputs: List[Tuple[str, int]],
                                  in_bits: int, out_bits: int) -> str:
    """Generate compact loop-based subtractor."""
    out_bytes = (out_bits + 7) // 8

    return f'''/*
 * Frozen {name} - Generated by TriX Forge (Compact)
 *
 * Polynomial subtraction: a - b = a + (~b) + 1
 */

#include "frozen_{name}.h"

static inline int poly_xor(int a, int b) {{ return a + b - 2*a*b; }}
static inline int poly_and(int a, int b) {{ return a * b; }}
static inline int poly_or(int a, int b) {{ return a + b - a*b; }}
static inline int poly_not(int a) {{ return 1 - a; }}

void frozen_{name}(const uint8_t *a, const uint8_t *b, uint8_t *result) {{
    int carry = 1;  /* +1 for two's complement */

    memset(result, 0, {out_bytes});

    for (int i = 0; i < {in_bits}; i++) {{
        int ai = (a[i >> 3] >> (i & 7)) & 1;
        int bi = (b[i >> 3] >> (i & 7)) & 1;
        int bi_inv = poly_not(bi);  /* Invert b */

        int ab_xor = poly_xor(ai, bi_inv);
        int sum_bit = poly_xor(ab_xor, carry);

        int ab_and = poly_and(ai, bi_inv);
        int carry_and_xor = poly_and(carry, ab_xor);
        carry = poly_or(ab_and, carry_and_xor);

        if (sum_bit)
            result[i >> 3] |= (1 << (i & 7));
    }}

    if (carry && {out_bits} > {in_bits})
        result[{in_bits} >> 3] |= (1 << ({in_bits} & 7));
}}
'''


def _generate_compact_bitwise(name: str, inputs: List[Tuple[str, int]],
                               outputs: List[Tuple[str, int]],
                               bits: int, op: str) -> str:
    """Generate compact loop-based bitwise operation."""
    out_bytes = (bits + 7) // 8

    if op == "xor":
        poly_call = "poly_xor(ai, bi)"
    elif op == "and":
        poly_call = "poly_and(ai, bi)"
    elif op == "or":
        poly_call = "poly_or(ai, bi)"
    else:
        poly_call = "0"

    return f'''/*
 * Frozen {name} - Generated by TriX Forge (Compact)
 *
 * Polynomial bitwise {op.upper()} operation.
 */

#include "frozen_{name}.h"

static inline int poly_xor(int a, int b) {{ return a + b - 2*a*b; }}
static inline int poly_and(int a, int b) {{ return a * b; }}
static inline int poly_or(int a, int b) {{ return a + b - a*b; }}

void frozen_{name}(const uint8_t *a, const uint8_t *b, uint8_t *result) {{
    memset(result, 0, {out_bytes});

    for (int i = 0; i < {bits}; i++) {{
        int ai = (a[i >> 3] >> (i & 7)) & 1;
        int bi = (b[i >> 3] >> (i & 7)) & 1;

        int out_bit = {poly_call};

        if (out_bit)
            result[i >> 3] |= (1 << (i & 7));
    }}
}}
'''
